export TORCH_DISTRIBUTED_DEBUG=INFO
export MIXED_PRECISION_TRAINING='bf16'
export NUM_GPUS=1
export NUM_NODES=1
export MAIN_PROCESS_PORT=29507
export HUGGINGFACE_MODEL_ID=stable-diffusion-v1-5/stable-diffusion-inpainting
export REFERENCE_NET=stable-diffusion-v1-5/stable-diffusion-v1-5
export REFERENCE_ENCODER_MODEL_ID=openai/clip-vit-base-patch32
export SINGLE_DATAPATH=/hosjiu/data/dresscode/DressCode
export VITONHD_DATAPATH=datasets/vitonhd
export DRESSCODE_DATAPATH=/hosjiu/data/dresscode/DressCode
export OUTPUT_DIR=results/Navier-1[alpha]
export PROJECT_NAME='TEST-VTO'
export WANDB_NAME_RUN='refnet'
export SNR_GAMMA=5
export WIDTH=384
export HEIGHT=512
export BATCH_SIZE=2
export SEED=2050
export ENABLE_TRACKER=false

python -u -m accelerate.commands.launch --main_process_port=$MAIN_PROCESS_PORT --mixed_precision=$MIXED_PRECISION_TRAINING --num_processes=$NUM_GPUS --num_machines=$NUM_NODES --dynamo_backend='no' \
train_refnet.py \
--pretrained_model_name_or_path=$HUGGINGFACE_MODEL_ID \
--refnet_model=$REFERENCE_NET \
--image_encoder_path=$REFERENCE_ENCODER_MODEL_ID \
--merge_hd_dc \
--use_subset \
--num_subset_samples=1000 \
--vitonhd_datapath=$VITONHD_DATAPATH \
--dresscode_datapath=$DRESSCODE_DATAPATH \
--width=$WIDTH \
--height=$HEIGHT \
--seed=$SEED \
--snr_gamma=$SNR_GAMMA \
--use_dilated_mask \
--use_densepose \
--allow_tf32 \
--train_with_8bit \
--output_dir=$OUTPUT_DIR \
--train_batch_size=$BATCH_SIZE \
--gradient_accumulation_steps=1 \
--mixed_precision=$MIXED_PRECISION_TRAINING \
--num_workers=16 \
--num_train_epochs=1000 \
--max_train_steps=300000 \
--checkpointing_steps=15000 \
--eval_steps=100000000 \
--validation_steps=2 \
--lr=1e-5 \
--use_tracker=$ENABLE_TRACKER \
--project_name=$PROJECT_NAME \
--wandb_name_run=$WANDB_NAME_RUN
