export TORCH_DISTRIBUTED_DEBUG=INFO
export MIXED_PRECISION_TRAINING='bf16'
export NUM_GPUS=4
export NUM_NODES=1
export MAIN_PROCESS_PORT=29507
export HUGGINGFACE_MODEL_ID=stable-diffusion-v1-5/stable-diffusion-inpainting
export SINGLE_DATAPATH=datasets/dresscode
export VITONHD_DATAPATH=datasets/vitonhd
export DRESSCODE_DATAPATH=datasets/dresscode
export OUTPUT_DIR=results/Navier-1[alpha]
export PROJECT_NAME='TEST-VTO'
export WANDB_NAME_RUN='refnet-(1024x768)'
export SNR_GAMMA=5
export WIDTH=768
export HEIGHT=1024
export BATCH_SIZE=4
export SEED=2048
export ENABLE_TRACKER=true

python -u -m accelerate.commands.launch --main_process_port=$MAIN_PROCESS_PORT --mixed_precision=$MIXED_PRECISION_TRAINING --num_processes=$NUM_GPUS --num_machines=$NUM_NODES --dynamo_backend='no' \
train_refnet.py \
--pretrained_model_name_or_path=$HUGGINGFACE_MODEL_ID \
--merge_hd_dc \
--use_subset \
--num_subset_samples=1000 \
--vitonhd_datapath=$VITONHD_DATAPATH \
--dresscode_datapath=$DRESSCODE_DATAPATH \
--width=$WIDTH \
--height=$HEIGHT \
--seed=$SEED \
--snr_gamma=$SNR_GAMMA \
--use_dilated_mask \
--use_densepose \
--allow_tf32 \
--train_with_8bit \
--output_dir=$OUTPUT_DIR \
--train_batch_size=$BATCH_SIZE \
--gradient_accumulation_steps=1 \
--mixed_precision=$MIXED_PRECISION_TRAINING \
--num_workers=16 \
--num_train_epochs=1000 \
--max_train_steps=300000 \
--checkpointing_steps=15000 \
--eval_steps=100000000 \
--validation_steps=10000000 \
--lr=1e-5 \
--use_tracker=$ENABLE_TRACKER \
--project_name=$PROJECT_NAME \
--wandb_name_run=$WANDB_NAME_RUN
